[package]
name = "onlyfriends-desktop"
version = "0.3.0"
edition = "2024"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus-native = { workspace = true, features = ["prelude"] }
dioxus-router.workspace = true
dioxus = { workspace = true, features = ["hooks", "macro"] }

storage-sqlite = { workspace = true }
client-core = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
ui = { workspace = true }
image.workspace = true
winit.workspace = true
winit-wayland.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
xdg.workspace = true

[features]
