[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-native = { git = "https://github.com/DioxusLabs/blitz", features = ["prelude"] }
dioxus-router = "0.7"
dioxus = { version = "0.7", default-features = false }  # satisfies macro internals

client-core = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
ui = { workspace = true }

[features]
# default = ["desktop"]
# desktop = ["dioxus/desktop"]

