[workspace]
resolver = "2"
members = ["client-core", "keystone", "relay", "ui/ui-common", "ui/mobile", "ui/web", "ui/desktop", "storage/storage-common", "storage/storage-sqlite", "examples/*"]

[workspace.dependencies]
dioxus = { version = "0.7.3" }
axum = "0.8"
base64 = "0.22.1"
chacha20poly1305 = "0.10"
clap = "4.6.1"
ed25519-dalek = "2"
hex = "0.4"
hkdf = "0.12"
postcard = "1"
rand = "0.8"
reqwest = "0.12"
rusqlite = "0.31"
serde = "1"
serde_json = "1"
sha2 = "0.10"
image = "^0.25.6"
mime = "0.3.17"
serde_with = "3.21.0"
tokio = "1"
tracing = "0.1.44"
x25519-dalek = "2"
tracing-subscriber = "0.3.23"
thiserror = "2.0.18"
xdg = "3.0.0"
winit = "0.30.13"

ui = { path = "ui/ui-common" }
client-core = { path = "client-core" }
storage-common = { path = "storage/storage-common" }
storage-sqlite = { path = "storage/storage-sqlite" }
keystone = { path = "keystone" }

[workspace.lints.clippy]
allow_attributes = "warn"
as_ptr_cast_mut = "warn"
as_underscore = "warn"
borrow_as_ptr = "warn"
implicit_clone = "warn"
undocumented_unsafe_blocks = "warn"
unicode_not_nfc = "warn"
unused_async = "deny"
wildcard_dependencies = "deny"

[workspace.lints.rust]
absolute_paths_not_starting_with_crate = "deny"
explicit_outlives_requirements = "warn"
macro_use_extern_crate = "deny"
missing_abi = "deny"
non_ascii_idents = "forbid"
rust_2018_idioms = { level = "deny", priority = -1 }
single_use_lifetimes = "warn"
unexpected_cfgs = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
