[package]
name = "client-core"
version = "0.1.0"
edition = "2024"

[dependencies]
base64.workspace = true
hex.workspace = true
keystone = { path = "../keystone" }
postcard = { workspace = true, features = ["alloc"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
