[package]
name = "client-core"
version = "0.1.0"
edition = "2024"

[dependencies]
hex.workspace = true
postcard = { workspace = true, features = ["alloc"] }
keystone = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
storage-common = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
onlyfriends-time = { workspace = true }
