[package]
name = "storage-sqlite"
version = "0.1.0"
edition = "2024"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite = { workspace = true, features = ["bundled"] }
storage-common = { workspace = true }
thiserror = { workspace = true }
keystone = { workspace = true }
mime = { workspace = true }
async-trait = { workspace = true }
