name: Rust CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always

jobs:
  # --- Formatting Check ---
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ hashFiles('flake.lock') }}

      - name: Check formatting
        run: nix develop --command cargo fmt -- --check

  # --- Linting with Clippy ---
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ hashFiles('flake.lock') }}

      - name: Run Clippy
        run: nix develop --command cargo clippy --all-targets --all-features -- -D warnings

  # --- Tests ---
  # TODO: Tests currently crash in the pipeline due to memory overflow, fix. See https://linear.app/ham-unlimited/issue/OF-29/fix-test-pipeline
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: DeterminateSystems/nix-installer-action@main

  #     - uses: DeterminateSystems/magic-nix-cache-action@main

  #     - uses: Swatinem/rust-cache@v2
  #       with:
  #         key: ${{ hashFiles('flake.lock') }}

  #     - name: Run tests
  #       run: nix develop --command cargo test --all-features
